### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by metanav** [Lansoweb/LosReCaptcha#4]
I am getting error:
Unable to enable crypto on TCP connection www.google.com: make sure the "sslcafile" or "sslcapath" option are properly set for the environment.

How can I  set 'sslcafile' or 'sslcapath' option in configuration?

**Comment by Lansoweb** [comment]
Hello! Actually, it is an zf2 issue, you can see more here: http://zend-framework-community.634137.n4.nabble.com/SSL-issue-td4660987.html

You can create a http client with the curl adapter and pass it to the ReCaptcha Service

**Comment by ivok** [comment]
When I use ZFCUser and in the cofiguration of zfc-user where I define to use your captcha 'form_captcha_options' => array('class'   => 'LosReCaptcha\Captcha\ReCaptcha'.....). How I supppouse to set the Curl adapter to be used instead of Socket. I actualy do not instantiate nowhere Recaptcha elelment in my code. It is done all automatically from zfc-user by the configuration were I set up to be used this captcha

Is it possible to add configuration to your module, which adapter to be used?

**Comment by Lansoweb** [comment]
@ivok Hi! the best approach is create a factory to create a are Captcha\ReCaptcha object, create the corresponding key in your service_manager => factories configuration and in the zfcuser use the factory. In the factory you can create the RecaptchaService with any configuration you like and inject it in the Recaptcha object.

**Comment by ivok** [comment]
@Lansoweb That should be the right way. Thank you very much

**Comment by Lansoweb** [comment]
@ivok You're welcome.
